import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/taskManagement.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable}font-sans antialiased`}
      >
        <main className="min-h-screen w-full bg-gradient-to-br from-gray-900 to-purple-600 px-4 sm:px-6 ">
          <AuthProvider>{children}</AuthProvider>
        </main>
      </body>
    </html>
  );
}
